services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - redis_data:/bitnami/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    restart: unless-stopeed
    networks: 
     - shortygo

volumes:
  redis_data:
    driver: local

networks:
  shortygo:
    driver: bridge